# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '2m4t_home' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 2m4t_home
  pod 'Alamofire', '~> 5.5'

end
